# Maven
- task: DownloadPackage@1
  inputs:
    packageType: 'maven'
    feed: '/73e0ec99-410c-4a60-b119-d5409f18714e'
    view: '1fd9ada1-8320-4388-a770-67b2f9a93e64'
    definition: 'mvn'
    version: 'v1'
    downloadPath: '$(System.ArtifactsDirectory)'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'install'
